"""empty message

Revision ID: 2039233ae102
Revises: 
Create Date: 2022-10-26 16:57:38.110037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2039233ae102'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rg21', sa.Integer(), nullable=True),
    sa.Column('rg20', sa.Integer(), nullable=True),
    sa.Column('rg16', sa.Integer(), nullable=True),
    sa.Column('anno', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_anno'), 'files', ['anno'], unique=False)
    op.create_index(op.f('ix_files_rg16'), 'files', ['rg16'], unique=False)
    op.create_index(op.f('ix_files_rg20'), 'files', ['rg20'], unique=False)
    op.create_index(op.f('ix_files_rg21'), 'files', ['rg21'], unique=False)
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_created'), 'history', ['created'], unique=False)
    op.create_index(op.f('ix_history_file_id'), 'history', ['file_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=32), nullable=True),
    sa.Column('cognome', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('nome_ufficio', sa.String(length=32), nullable=True),
    sa.Column('ufficio', sa.String(length=32), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_cognome'), 'user', ['cognome'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_nome'), 'user', ['nome'], unique=False)
    op.create_index(op.f('ix_user_nome_ufficio'), 'user', ['nome_ufficio'], unique=False)
    op.create_index(op.f('ix_user_ufficio'), 'user', ['ufficio'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_ufficio'), table_name='user')
    op.drop_index(op.f('ix_user_nome_ufficio'), table_name='user')
    op.drop_index(op.f('ix_user_nome'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_cognome'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_history_file_id'), table_name='history')
    op.drop_index(op.f('ix_history_created'), table_name='history')
    op.drop_table('history')
    op.drop_index(op.f('ix_files_rg21'), table_name='files')
    op.drop_index(op.f('ix_files_rg20'), table_name='files')
    op.drop_index(op.f('ix_files_rg16'), table_name='files')
    op.drop_index(op.f('ix_files_anno'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
