"""user modified

Revision ID: 30b4ee631a6e
Revises: 
Create Date: 2022-10-18 11:45:19.505644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b4ee631a6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_code'), 'files', ['code'], unique=False)
    op.create_index(op.f('ix_files_created'), 'files', ['created'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=32), nullable=True),
    sa.Column('cognome', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('nome_ufficio', sa.String(length=32), nullable=True),
    sa.Column('ufficio', sa.String(length=32), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_cognome'), 'user', ['cognome'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_nome'), 'user', ['nome'], unique=False)
    op.create_index(op.f('ix_user_nome_ufficio'), 'user', ['nome_ufficio'], unique=False)
    op.create_index(op.f('ix_user_ufficio'), 'user', ['ufficio'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_ufficio'), table_name='user')
    op.drop_index(op.f('ix_user_nome_ufficio'), table_name='user')
    op.drop_index(op.f('ix_user_nome'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_cognome'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_files_created'), table_name='files')
    op.drop_index(op.f('ix_files_code'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
