"""Modifica modello Files

Revision ID: aedecfc1b481
Revises: 8bf3c6f787a1
Create Date: 2022-10-11 15:26:24.319173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aedecfc1b481'
down_revision = '8bf3c6f787a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('user_name', sa.String(length=64), nullable=True))
    op.add_column('files', sa.Column('user_office', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_files_user_name'), 'files', ['user_name'], unique=False)
    op.create_index(op.f('ix_files_user_office'), 'files', ['user_office'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_user_office'), table_name='files')
    op.drop_index(op.f('ix_files_user_name'), table_name='files')
    op.drop_column('files', 'user_office')
    op.drop_column('files', 'user_name')
    # ### end Alembic commands ###
